"""Tool for spawning sibling agent containers."""

import asyncio
import logging
import os
import secrets
import uuid

import httpx
from google.adk.tools.tool_context import ToolContext

logger = logging.getLogger(__name__)

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SPAWN_DIR = os.path.abspath("./data/spawns")
IMAGE_NAME = "ori-agent-image"


async def spawn_agent(
    bot_name: str,
    purpose: str,
    tool_context: ToolContext = None,
    model_overrides: str = "",
) -> dict:
    """Spawn a new sibling agent as a Docker container.

    The new agent shares credentials via the host env file (never exposed to LLM)
    and gets its own unique BOT_NAME, A2A_API_KEY, and data directory.
    After boot, this agent automatically adds it as an A2A friend.

    Args:
        bot_name: Name for the new agent (e.g. 'Scout', 'Analyst'). Must be unique.
        purpose: What this agent is for (added to its .env as AGENT_PURPOSE).
        model_overrides: Optional comma-separated model overrides, e.g.
            'CoordinatorAgent=anthropic/claude-sonnet-4-6,DeveloperAgent=google/gemini-3-flash-preview'

    Returns:
        dict: Status, container ID, and A2A connection info.
    """
    # Sanitize bot name
    safe_name = bot_name.strip().replace(" ", "-").lower()
    if not safe_name:
        return {"status": "error", "message": "bot_name is required."}

    container_name = f"ori-{safe_name}"

    # Check if container already exists
    check = await asyncio.create_subprocess_exec(
        "docker", "ps", "-a", "--filter", f"name=^/{container_name}$", "--format", "{{.ID}}",
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    stdout, _ = await check.communicate()
    if stdout.strip():
        return {"status": "error", "message": f"Container '{container_name}' already exists. Remove it first or choose a different name."}

    # Create spawn data directory
    spawn_data = os.path.join(SPAWN_DIR, safe_name)
    os.makedirs(spawn_data, exist_ok=True)

    # Generate unique credentials for the child
    child_a2a_key = secrets.token_urlsafe(32)
    child_passcode = secrets.token_urlsafe(16)

    # Parent identity — the child needs to recognize the parent as admin
    parent_bot_name = os.environ.get("BOT_NAME", "Ori")
    parent_a2a_id = os.environ.get("A2A_AGENT_ID", f"ori-{parent_bot_name.lower()}")
    parent_a2a_key = os.environ.get("A2A_API_KEY", "")
    parent_admin_ids = os.environ.get("ADMIN_USER_IDS", "")

    # Build the child's .env from parent's env file + overrides
    # The parent's .env is read by Docker (--env-file), NOT by the LLM.
    # We only write child-specific values to the child's .env.
    child_env_path = os.path.join(spawn_data, ".env")

    # Merge admin IDs: human admin + parent agent
    admin_ids = [aid.strip() for aid in parent_admin_ids.split(",") if aid.strip()]
    if parent_a2a_id not in admin_ids:
        admin_ids.append(parent_a2a_id)
    merged_admin_ids = ",".join(admin_ids)

    # Child gets half the parent's RPM by default to protect shared quota
    parent_rpm = int(os.environ.get("AGENT_RPM", "30"))
    child_rpm = max(10, parent_rpm // 2)

    child_env_lines = [
        "# Auto-generated by parent agent spawn",
        f"BOT_NAME={bot_name}",
        f"A2A_API_KEY={child_a2a_key}",
        f"ADMIN_PASSCODE={child_passcode}",
        f"AGENT_PURPOSE={purpose}",
        f"ADMIN_USER_IDS={merged_admin_ids}",
        f"AGENT_RPM={child_rpm}",
    ]

    # Add model overrides
    if model_overrides:
        for override in model_overrides.split(","):
            override = override.strip()
            if "=" in override:
                component, model = override.split("=", 1)
                child_env_lines.append(f"MODEL_{component.strip().upper()}={model.strip()}")

    with open(child_env_path, "w") as f:
        f.write("\n".join(child_env_lines) + "\n")

    # Pre-seed parent as a friend in the child's data directory
    # so the child recognizes and trusts the parent from first boot
    import json
    from datetime import datetime

    parent_base_url = os.environ.get("A2A_BASE_URL", "")
    friends_path = os.path.join(spawn_data, "friends.json")
    friends = {
        parent_bot_name.lower(): {
            "name": parent_bot_name,
            "url": parent_base_url,
            "agent_id": parent_a2a_id,
            "added_at": datetime.utcnow().isoformat(),
            "relationship": "parent",
        }
    }
    with open(friends_path, "w") as f:
        json.dump(friends, f, indent=2)

    # Store parent's A2A API key so the child can authenticate calls from parent
    keys_path = os.path.join(spawn_data, "a2a_keys.json")
    if parent_a2a_key:
        with open(keys_path, "w") as f:
            json.dump({parent_bot_name.lower(): parent_a2a_key}, f, indent=2)

    # Copy ADC credentials to child's data dir if available
    parent_adc = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "")
    if parent_adc and os.path.isfile(parent_adc):
        import shutil as _shutil
        child_adc = os.path.join(spawn_data, ".adc.json")
        _shutil.copy2(parent_adc, child_adc)

    # Parent's env file provides shared credentials (API keys, tokens)
    parent_env_file = os.environ.get("DOTENV_PATH", "./data/.env")
    parent_env_abs = os.path.abspath(parent_env_file)

    # Pick a random port for the child's A2A server
    # Port 0 = Docker assigns a random available port
    agent_port = "0"

    # Build docker run command
    # The child gets:
    #   1. Parent's env file for shared creds (GOOGLE_API_KEY, ANTHROPIC_API_KEY, etc.)
    #   2. Its own data dir with its own .env (overrides BOT_NAME, A2A_API_KEY, etc.)
    #   3. The child's .env takes precedence because DOTENV_PATH points to it
    run_cmd = [
        "docker", "run", "-d",
        "--name", container_name,
        "--label", "project=ori",
        "--label", f"ori.parent={os.environ.get('BOT_NAME', 'Ori')}",
        "--label", f"ori.purpose={purpose}",
        "--env-file", parent_env_abs,
        "-e", f"DOTENV_PATH=/code/data/.env",
        "-e", f"BOT_NAME={bot_name}",
        "-e", f"A2A_API_KEY={child_a2a_key}",
        "-e", f"ADMIN_PASSCODE={child_passcode}",
        "-e", "GOOGLE_APPLICATION_CREDENTIALS=/code/data/.adc.json",
        "-v", f"{spawn_data}:/code/data:z",
        "-v", "/var/run/docker.sock:/var/run/docker.sock",
        "-p", f"{agent_port}:8000",
        "--restart", "unless-stopped",
        IMAGE_NAME,
    ]

    proc = await asyncio.create_subprocess_exec(
        *run_cmd,
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()

    if proc.returncode != 0:
        err = stderr.decode().strip()
        return {"status": "error", "message": f"Failed to spawn container: {err}"}

    container_id = stdout.decode().strip()[:12]

    # Wait for the child's A2A server to come up
    child_url = None
    for attempt in range(15):
        await asyncio.sleep(2)
        # Get the mapped port
        port_cmd = await asyncio.create_subprocess_exec(
            "docker", "port", container_name, "8000",
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
        )
        port_out, _ = await port_cmd.communicate()
        port_str = port_out.decode().strip()
        if not port_str:
            continue

        # Parse "0.0.0.0:XXXXX" -> port
        mapped_port = port_str.split(":")[-1]
        child_url = f"http://localhost:{mapped_port}"

        # Try to reach the agent card
        try:
            async with httpx.AsyncClient(timeout=5) as client:
                resp = await client.get(f"{child_url}/.well-known/agent.json")
                if resp.status_code == 200:
                    break
        except Exception:
            child_url = None
            continue

    if not child_url:
        return {
            "status": "partial",
            "message": f"Container '{container_name}' started (ID: {container_id}) but A2A server not yet reachable. Try adding as friend manually later.",
            "container_id": container_id,
            "container_name": container_name,
        }

    # Auto-add as friend
    from app.tools.a2a import add_friend
    friend_result = await add_friend(
        url=child_url,
        name=safe_name,
        tool_context=tool_context,
    )

    return {
        "status": "success",
        "message": f"Agent '{bot_name}' spawned and connected.",
        "container_id": container_id,
        "container_name": container_name,
        "a2a_url": child_url,
        "friend_registration": friend_result,
    }


async def list_spawned_agents(tool_context: ToolContext = None) -> dict:
    """List all spawned sibling agent containers and their status."""
    proc = await asyncio.create_subprocess_exec(
        "docker", "ps", "-a",
        "--filter", "label=project=ori",
        "--filter", f"label=ori.parent",
        "--format", "{{.Names}}\t{{.Status}}\t{{.Ports}}\t{{.Label \"ori.purpose\"}}",
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()

    if proc.returncode != 0:
        return {"status": "error", "message": stderr.decode().strip()}

    agents = []
    for line in stdout.decode().strip().split("\n"):
        if not line.strip():
            continue
        parts = line.split("\t")
        agents.append({
            "name": parts[0] if len(parts) > 0 else "",
            "status": parts[1] if len(parts) > 1 else "",
            "ports": parts[2] if len(parts) > 2 else "",
            "purpose": parts[3] if len(parts) > 3 else "",
        })

    return {"status": "success", "agents": agents, "count": len(agents)}


async def stop_spawned_agent(
    container_name: str,
    remove: bool = False,
    tool_context: ToolContext = None,
) -> dict:
    """Stop a spawned sibling agent. Optionally remove container and all data.

    Args:
        container_name: The container name (e.g. 'ori-scout').
        remove: If True, remove the container AND delete its data directory.
            This is irreversible — the agent's state, memory, and credentials are gone.
    """
    # Safety: only allow stopping containers with the ori parent label
    check = await asyncio.create_subprocess_exec(
        "docker", "inspect", "--format", "{{.Config.Labels}}", container_name,
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    stdout, _ = await check.communicate()
    if "ori.parent" not in stdout.decode():
        return {"status": "error", "message": f"'{container_name}' is not a spawned agent or doesn't exist."}

    stop = await asyncio.create_subprocess_exec(
        "docker", "stop", container_name,
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    await stop.communicate()

    if not remove:
        return {"status": "success", "message": f"Agent '{container_name}' stopped. Use remove=True to delete permanently."}

    # Remove container
    rm = await asyncio.create_subprocess_exec(
        "docker", "rm", container_name,
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    await rm.communicate()

    # Delete spawn data directory
    # Container name is "ori-{safe_name}", extract the safe_name
    safe_name = container_name.removeprefix("ori-")
    spawn_data = os.path.join(SPAWN_DIR, safe_name)
    cleanup_msg = ""
    if os.path.exists(spawn_data):
        import shutil
        shutil.rmtree(spawn_data, ignore_errors=True)
        cleanup_msg = " Data directory deleted."

    # Remove from friends list
    from app.tools.a2a import FRIENDS_FILE, KEYS_FILE
    for fpath in (FRIENDS_FILE, KEYS_FILE):
        if os.path.exists(fpath):
            try:
                import json
                with open(fpath) as f:
                    data = json.load(f)
                if safe_name in data:
                    del data[safe_name]
                    with open(fpath, "w") as f:
                        json.dump(data, f, indent=2)
            except Exception:
                pass

    return {"status": "success", "message": f"Agent '{container_name}' stopped, removed, and cleaned up.{cleanup_msg}"}
