"""Multimodal YouTube summarization tool using Gemini 2.0+."""

import logging
import os
from google import genai
from google.genai import types
from app.app_utils.models import get_model_name, _is_vertex_mode

logger = logging.getLogger(__name__)

async def youtube_summary(url: str, query: str):
    """
    Answer questions about a specific YouTube video, focusing on a specific query.
    This tool summarizes both VISUAL and audio sources from YouTube.
    
    Args:
        url (str): A YouTube video URL.
        query (str): The query or question to answer about the video content.
    """
    try:
        # Resolve model name and auth
        model_name = get_model_name("youtube_summarizer")
        is_vertex = _is_vertex_mode()
        
        # Initialize client based on auth mode
        if is_vertex:
            client = genai.Client(vertexai=True, project=os.environ.get("GOOGLE_CLOUD_PROJECT"), location=os.environ.get("GOOGLE_CLOUD_LOCATION"))
        else:
            api_key = os.environ.get("GOOGLE_API_KEY")
            client = genai.Client(api_key=api_key)

        # Gemini 2.0+ supports processing YouTube URLs directly via file_data
        response = await client.aio.models.generate_content(
            model=model_name,
            contents=[
                types.Part.from_uri(file_uri=url, mime_type="video/mp4"),
                types.Part.from_text(text=query),
            ],
        )

        if not response or not response.candidates:
            return {"status": "failed", "message": "No response generated by the model."}

        candidate = response.candidates[0]
        if candidate.finish_reason != "STOP":
            return {
                "status": "failed",
                "message": f"Generation did not finish normally. Reason: {candidate.finish_reason}"
            }

        response_text = "".join(part.text for part in candidate.content.parts if part.text)
        return {"status": "success", "message": response_text}

    except Exception as e:
        logger.error("YouTube summary failed: %s", e)
        return {"status": "error", "message": str(e)}
