"""V2 scheduler — OneOffReminder template.

Phase 9 slice 2 per ``docs/PHASE_9_PLAN.md`` §1.2 + §3.2.

Builds the first end-to-end working ScheduleSpec shape:
an emit-only reminder that fires once at a specified
UTC datetime and delivers a text payload to a channel.

Surface:

- :data:`ONE_OFF_REMINDER_TEMPLATE_NAME` /
  :data:`ONE_OFF_REMINDER_TEMPLATE_VERSION` — the
  documented :class:`TemplateRef` identity for the
  template; matched verbatim by the worker emit branch
  (slice 5) and the authoring tool wrapper (slice 3).
- :class:`OneOffReminderArgs` — typed Pydantic model for
  the ``TemplateRef.args`` dict. Phase 9 carries a
  single ``text`` field (1-4000 chars). Future fields
  (e.g. ``snoozable``) land alongside their behaviour
  in later phases.
- :func:`build_one_off_reminder` — pure-Python builder.
  Returns a frozen :class:`ScheduleSpec` with
  ``.with_fresh_hash()`` populated.

Design choices:

- Delivery target is ``recipient.external_id`` — the
  field name on the phase-1 :class:`ChannelRef` model
  (round-1 reviewer L98 fix).
- Naive ``at`` is rejected at the builder layer with a
  clear ``ValueError`` so test rigs see the failure
  before pydantic ever sees the bad value. The authoring
  tool wrapper (slice 3) maps this to
  ``validation_failed(naive_at_datetime)``.
- ``clock()`` is the sole authority for ``authored_at``;
  phase-5 hard rule 10 keeps the module clock-pure
  (AST pin in the tests).
- No vendor SDK imports at module load — DI
  protocol-typed (Slack / Google client wiring lives in
  the authoring tool wrapper + emit adapter slices, not
  here).

References:
- ``docs/CONTRACTS_V2_DESIGN.md`` §5.2 (template-first
  authoring; ``TemplateRef.args``).
- ``docs/PHASE_9_PLAN.md`` §1.2 / §3.2 / §5.1.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Callable

from pydantic import BaseModel, ConfigDict, Field

from app.v2.enums import DeliveryFallbackPolicy, FailureActionType
from app.v2.models.common import (
    AuditPolicy,
    ChannelRef,
    Delivery,
    FailurePolicy,
    TemplateRef,
    UserRef,
)
from app.v2.models.schedule import ScheduleSpec
from app.v2.models.triggers import OneOffTrigger


ONE_OFF_REMINDER_TEMPLATE_NAME = "OneOffReminder"
ONE_OFF_REMINDER_TEMPLATE_VERSION = "1"

_TEXT_MAX_LENGTH = 4000


class OneOffReminderArgs(BaseModel):
    """Typed payload carried on ``TemplateRef.args`` for
    OneOffReminder specs.

    Phase 9 ships a single field; future fields land
    alongside their behaviour (``snoozable`` etc.).
    """

    model_config = ConfigDict(extra="forbid")

    text: str = Field(min_length=1, max_length=_TEXT_MAX_LENGTH)


def build_one_off_reminder(
    *,
    at: datetime,
    recipient: ChannelRef,
    text: str,
    owner: UserRef,
    schedule_id: str,
    audit: AuditPolicy | None = None,
    failure: FailurePolicy | None = None,
    clock: Callable[[], datetime],
) -> ScheduleSpec:
    """Build a frozen :class:`ScheduleSpec` for a OneOff
    reminder.

    Args:
        at: When the reminder fires. MUST be tz-aware UTC
            (``utcoffset() == timedelta(0)``). Naive
            datetimes and non-UTC offsets raise
            ``ValueError`` BEFORE any spec construction.
        recipient: Slack / Telegram / etc. destination.
            The phase-1 :class:`ChannelRef` carries
            ``kind`` + ``external_id``; the builder uses
            ``recipient.external_id`` for the delivery
            target (round-1 reviewer L98 fix).
        text: Reminder body. Validated by
            :class:`OneOffReminderArgs` (1-4000 chars).
        owner: Author / owner identity.
        schedule_id: The schedule's stable id. Must be
            generated by the caller (typically the
            ``schedule_id_factory`` injected on the
            authoring tool wrapper).
        audit: Audit policy. Defaults to
            :class:`AuditPolicy` defaults.
        failure: Failure policy. Defaults to
            ``alert_admin``.
        clock: Tz-aware UTC clock — sole authority for
            ``authored_at``. Naive output raises via the
            ScheduleSpec layer (phase-7 round-1 L145).

    Returns:
        Frozen ``ScheduleSpec`` with ``.with_fresh_hash()``
        populated, ``execution_plan_hash=None``,
        ``template=TemplateRef(name="OneOffReminder",
        version="1", args={"text": text})``.

    Raises:
        ValueError: ``at`` is naive or non-UTC.
        pydantic.ValidationError: ``text`` violates the
            :class:`OneOffReminderArgs` constraints.
    """
    # ---- 1. ``at`` UTC enforcement ----
    if (
        at.tzinfo is None
        or at.tzinfo.utcoffset(at) is None
    ):
        raise ValueError(
            "build_one_off_reminder: `at` must be tz-aware "
            "UTC (got naive datetime)"
        )
    # Normalise non-UTC offsets to UTC so the trigger
    # carries a clean +00:00 wall clock. ScheduleSpec
    # validation rejects naive; normalising non-UTC keeps
    # the rest of the pipeline consistent with the phase-8
    # clock-handling pattern.
    at_utc = at.astimezone(timezone.utc)

    # ---- 2. Args validation ----
    args = OneOffReminderArgs(text=text)

    # ---- 3. Defaults ----
    if audit is None:
        audit = AuditPolicy()
    if failure is None:
        failure = FailurePolicy(
            on_failure_action=FailureActionType.ALERT_ADMIN
        )

    # ---- 4. Build spec ----
    clock_value = clock()
    if (
        clock_value.tzinfo is None
        or clock_value.tzinfo.utcoffset(clock_value) is None
    ):
        raise ValueError(
            "build_one_off_reminder: clock() returned a "
            "naive datetime; authored_at must be tz-aware "
            "UTC"
        )
    authored_at = clock_value.astimezone(timezone.utc).isoformat()

    # ScheduleSpec.description requires >=8 chars after
    # strip; OneOffReminderArgs.text is min_length=1 so a
    # short text would fail the spec validator. Prefix
    # with the template name so the description stays
    # human-readable AND always meets the minimum length.
    description = f"OneOffReminder: {text}"

    spec = ScheduleSpec(
        id=schedule_id,
        description=description,
        owner=owner,
        trigger=OneOffTrigger(
            at_iso_datetime=at_utc,
            timezone="UTC",
        ),
        delivery=Delivery(
            target_session_id=recipient.external_id,
            fallback_policy=(
                DeliveryFallbackPolicy.SESSION_TO_ORIGIN
            ),
        ),
        failure=failure,
        audit=audit,
        # status omitted — picks up the model default (ACTIVE).
        execution_plan_hash=None,
        template=TemplateRef(
            name=ONE_OFF_REMINDER_TEMPLATE_NAME,
            version=ONE_OFF_REMINDER_TEMPLATE_VERSION,
            args=args.model_dump(),
        ),
        parent_hash=None,
        authored_at=authored_at,
    )
    return spec.with_fresh_hash()


__all__ = [
    "ONE_OFF_REMINDER_TEMPLATE_NAME",
    "ONE_OFF_REMINDER_TEMPLATE_VERSION",
    "OneOffReminderArgs",
    "build_one_off_reminder",
]
